### ISSUE TITLE
Fix bug - https links have http:// prepended to them

### ISSUE THREAD

**Issue by ateich** [PresentPath/Linkd#42]
When links that begin with "https://" are added, they have "http://" prepended to them resulting in "http://https://".

**Comment by ateich** [comment]
It looks like this could be solved by changing line 38 in client/src/js/components/LinkDetail.js
from: 

``` javascript
let url = link.url.search(/^http:\/\//) !== 0 ? 'http://' + link.url : link.url;
```

to:

``` javascript
let url = link.url.search(/^https?:\/\//) !== 0 ? 'http://' + link.url : link.url;
```

Adding s? to the regex allows it to search for http and optionally add the s.

**Comment by kuychaco** [comment]
@ateich thanks! Fixed the bug :+1:
